/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.utp.misiontic2022.lgutierrez.vista.gui;

import co.edu.utp.misiontic2022.lgutierrez.controlador.RestauranteGUIController;
import co.edu.utp.misiontic2022.lgutierrez.exception.PagoException;
import co.edu.utp.misiontic2022.lgutierrez.modelo.*;
import co.edu.utp.misiontic2022.lgutierrez.vista.gui.modelbui.PedidoTableModel;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Laura
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    private RestauranteGUIController controlador;
    private PedidoTableModel pedidoTableModel;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        
        setSize(800, 600);
        setLocationRelativeTo(null);
        
        this.controlador = new RestauranteGUIController();
        
        //Cargar datos
        limpiarDatosMesa();
        
        cargarListaMesas();
        cargarCombosComida();
        
        //Inicializar la tabla
        this.pedidoTableModel = new PedidoTableModel();
        tblPedidos.setModel(this.pedidoTableModel);
        
        //Para que en la tabla solo se puede seleccionar un elemento a la vez
        tblPedidos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblPedidos.getSelectionModel().addListSelectionListener(evt -> seleccionarPedido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnNuevoPedido = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtValorMesa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spnEfectivo = new javax.swing.JSpinner();
        btnPagar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDevuelta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMesas = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnEntregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbSopa = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmbPrincipio = new javax.swing.JComboBox<>();
        chkEnsalada = new javax.swing.JCheckBox();
        cmbEnsalada = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cmbJugo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbCarne = new javax.swing.JComboBox<>();
        txtCliente = new javax.swing.JTextField();
        btnGuardarPedido = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        javax.swing.JComboBox<Adicional> cmbAdicionar = new javax.swing.JComboBox<>();
        btnAgregarAdicional = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante El Corrientazo");
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesas"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btnNuevoPedido.setText("Nuevo Pedido");
        btnNuevoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPedidoActionPerformed(evt);
            }
        });
        jPanel4.add(btnNuevoPedido);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuenta"));

        jLabel1.setText("Valor a pagar:");

        txtValorMesa.setEditable(false);
        txtValorMesa.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtValorMesa.setText("0");

        jLabel2.setText("Efectivo: ");

        spnEfectivo.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 500));

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        jLabel3.setText("Devuelta: ");

        txtDevuelta.setEditable(false);
        txtDevuelta.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtDevuelta.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(txtValorMesa)
                            .addComponent(txtDevuelta))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValorMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDevuelta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        lstMesas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstMesas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstMesasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstMesas);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedidos"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btnEntregar.setText("Entregar");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });
        jPanel6.add(btnEntregar);

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setViewportView(tblPedidos);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        jLabel8.setText("Cliente: ");

        jLabel10.setText("Sopa:");

        jLabel11.setText("Principio:");

        chkEnsalada.setSelected(true);
        chkEnsalada.setText("Ensalada:");
        chkEnsalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEnsaladaActionPerformed(evt);
            }
        });

        jLabel12.setText("Jugo:");

        jLabel13.setText("Carne:");

        txtCliente.setToolTipText("");

        btnGuardarPedido.setText("Guardar");
        btnGuardarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPedidoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Adicionales");

        btnAgregarAdicional.setText("Agregar");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setPreferredSize(new java.awt.Dimension(100, 80));
        jScrollPane5.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(chkEnsalada)
                                                .addComponent(jLabel13))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cmbEnsalada, 0, 139, Short.MAX_VALUE)
                                                .addComponent(cmbCarne, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(cmbAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnAgregarAdicional))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel12))
                                            .addGap(40, 40, 40)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cmbSopa, javax.swing.GroupLayout.Alignment.TRAILING, 0, 139, Short.MAX_VALUE)
                                                .addComponent(cmbJugo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cmbPrincipio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtCliente))))
                                    .addGap(6, 6, 6))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(cmbSopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbPrincipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(cmbCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEnsalada)
                    .addComponent(cmbEnsalada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbJugo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarPedido)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarAdicional))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel13, jLabel8});

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstMesasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstMesasValueChanged
        // TODO add your handling code here:
        var mesa = lstMesas.getSelectedValue();
        if (mesa != null) {
            cargarDatosMesa(mesa);
        } else{
            limpiarDatosMesa();
        }
    }//GEN-LAST:event_lstMesasValueChanged

    private void btnGuardarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPedidoActionPerformed
        // TODO: Validar campos obligatorios
        
        try{
            //Enviar a guardar a ka base de datos
            var mesa = lstMesas.getSelectedValue();
            Corrientazo almuerzo = null;
            if (chkEnsalada.isSelected()) {
                almuerzo = new Corrientazo(12_000, 
                        (OpcionSopa)cmbSopa.getSelectedItem(),
                        (OpcionPrincipio)cmbPrincipio.getSelectedItem(), 
                        (OpcionCarne)cmbCarne.getSelectedItem(),
                        (OpcionEnsalada)cmbEnsalada.getSelectedItem(),
                        (OpcionJugo)cmbJugo.getSelectedItem());
            } else {
                almuerzo = new Corrientazo(12_000, 
                        (OpcionSopa)cmbSopa.getSelectedItem(),
                        (OpcionPrincipio)cmbPrincipio.getSelectedItem(), 
                        (OpcionCarne)cmbCarne.getSelectedItem(),
                        (OpcionJugo)cmbJugo.getSelectedItem());
            }

            var pedido = new Pedido(txtCliente.getText(), almuerzo);

            controlador.guardarPedido(mesa, pedido);

            //Actualiar la tabla de pedidos
            this.pedidoTableModel.addDato(pedido);
            mostrarMensaje("Pedido agregado exitosamente");
        
        } catch(SQLException ex){
            mostrarError("Error guardando pedido", ex);
        }
    }//GEN-LAST:event_btnGuardarPedidoActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        // TODO add your handling code here:
        if(tblPedidos.getSelectedRowCount() == 1){
            try{
                var row = tblPedidos.getSelectedRow();
                var pedido = this.pedidoTableModel.getDato(row);
                controlador.entregarPedido(pedido);
                
                this.pedidoTableModel.setDato(row, pedido);
                lstMesasValueChanged(null);
                
                mostrarMensaje("El pedido se ha entregado exitosamente");
            } catch(SQLException ex){
                mostrarError("Error entregando pedido", ex);
            }
        }
    }//GEN-LAST:event_btnEntregarActionPerformed

    private void chkEnsaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEnsaladaActionPerformed
        if (!chkEnsalada.isSelected()) {
            cmbEnsalada.setEnabled(false);
            cmbEnsalada.setSelectedIndex(-1);
        } else {
            cmbEnsalada.setEnabled(true);
        }
    }//GEN-LAST:event_chkEnsaladaActionPerformed

    private void btnNuevoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPedidoActionPerformed
        if (lstMesas.getSelectedValue() != null) {
            tblPedidos.clearSelection();
            limpiarCamposPedido();
            //Para que la caja quede con el cursor
            txtCliente.requestFocus();
        } else{
            mostrarAdvertencia("Debe seleccionar una mesa");
        }
    }//GEN-LAST:event_btnNuevoPedidoActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        try {
            var mesa = lstMesas.getSelectedValue();
            var efectivo = (Integer)spnEfectivo.getValue();
            var devuelta = controlador.pagar(mesa, efectivo);
            
            txtDevuelta.setText(String.format("$ %,d", devuelta));
            mostrarMensaje("La cuenta se ha pagado por completo");
            
            lstMesas.clearSelection();
            lstMesasValueChanged(null);
            
        } catch (SQLException | PagoException ex) {
            mostrarError("Error al pagar cuenta", ex);
        } 
    }//GEN-LAST:event_btnPagarActionPerformed

    private void cargarListaMesas(){
        try {
            var mesas = controlador.listarMesas();
            lstMesas.removeAll();
            var modelo = new DefaultListModel<Mesa>();
            modelo.addAll(mesas);
            lstMesas.setModel(modelo);
            
        } catch (SQLException ex) {
            mostrarError("Error listando mesas", ex);
        }
    }
    
    private void cargarDatosMesa(Mesa mesa){
        try {
            //Cargar el valor a pagar
            var valor = controlador.calcularTotalMesa(mesa);
            txtValorMesa.setText(String.format("$ %,d", valor));
            
            //Cargar los pedidos de la mesa
            var pedidos = controlador.listarPedidos(mesa);
            pedidoTableModel.setDatos(pedidos);
            
        } catch (SQLException ex) {
            mostrarError("Error consultando cuenta de mesa", ex);
        }
    }
    
    private void limpiarDatosMesa(){
        txtValorMesa.setText(String.format("$ %,d", 0));
        spnEfectivo.setValue(0);
        txtDevuelta.setText(String.format("$ %,d", 0));
    }
    
    private void seleccionarPedido() {
        if (tblPedidos.getSelectedRowCount() == 1) {
            //Cargar la información del pedido en el formulario
            var pedido = pedidoTableModel.getDato(tblPedidos.getSelectedRow());
            
            txtCliente.setText(pedido.getCliente());
            cmbSopa.setSelectedItem(pedido.getAlmuerzo().getSopa());
            cmbPrincipio.setSelectedItem(pedido.getAlmuerzo().getPrincipio());
            cmbCarne.setSelectedItem(pedido.getAlmuerzo().getCarne());
            
            if (pedido.getAlmuerzo().getEnsalada() == null) {
                chkEnsalada.setSelected(false);
            } else{
                chkEnsalada.setSelected(true);
                cmbEnsalada.setSelectedItem(pedido.getAlmuerzo().getEnsalada());
            }
            
            chkEnsaladaActionPerformed(null);
            cmbJugo.setSelectedItem(pedido.getAlmuerzo().getJugo());
            
            //TODO: Agregar los adicionales a la tabla
            
        } else {
            //Limpiar los datos del pedido 
            limpiarCamposPedido();
            
            //TODO: Limpiar los adicionales
        }
    }
    
    private void limpiarCamposPedido(){
        txtCliente.setText("");
        cmbSopa.setSelectedIndex(-1);
        cmbPrincipio.setSelectedIndex(-1);
        cmbCarne.setSelectedIndex(-1);
        cmbEnsalada.setSelectedIndex(-1);
        cmbJugo.setSelectedIndex(-1);
    }
    
    private void cargarCombosComida(){
        try{
            cmbSopa.removeAllItems();
            controlador.listarSopas().forEach(cmbSopa::addItem);
            
            cmbPrincipio.removeAllItems();
            controlador.listarPrincipios().forEach(cmbPrincipio::addItem);
            
            cmbCarne.removeAllItems();
            controlador.listarCarnes().forEach(cmbCarne::addItem);
            
            cmbEnsalada.removeAllItems();
            controlador.listarEnsaladas().forEach(cmbEnsalada::addItem);
            
            cmbJugo.removeAllItems();
            controlador.listarJugos().forEach(cmbJugo::addItem);
            
            
            
        } catch(SQLException ex){
            mostrarError("Error consultadndo alimentos", ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAdicional;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnGuardarPedido;
    private javax.swing.JButton btnNuevoPedido;
    private javax.swing.JButton btnPagar;
    private javax.swing.JCheckBox chkEnsalada;
    private javax.swing.JComboBox<OpcionCarne> cmbCarne;
    private javax.swing.JComboBox<OpcionEnsalada> cmbEnsalada;
    private javax.swing.JComboBox<OpcionJugo> cmbJugo;
    private javax.swing.JComboBox<OpcionPrincipio> cmbPrincipio;
    private javax.swing.JComboBox<OpcionSopa> cmbSopa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JList<Mesa> lstMesas;
    private javax.swing.JSpinner spnEfectivo;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDevuelta;
    private javax.swing.JTextField txtValorMesa;
    // End of variables declaration//GEN-END:variables

    private void mostrarError(String error, Exception ex) {
        JOptionPane.showMessageDialog(this, error + ": " + ex.getMessage(), 
                "Restaurante el Corrientazo", JOptionPane.ERROR_MESSAGE);
    }
    
    private void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, 
                "Restaurante el Corrientazo", JOptionPane.INFORMATION_MESSAGE);
    }

    private void mostrarAdvertencia(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, 
                "Restaurante el Corrientazo", JOptionPane.WARNING_MESSAGE);
    }

    
}
